[[starred]]
id = "e55c6aa7-1103-4d48-8457-12f5cafe62ac"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T05:39:58.353270+00:00"
pinned = true

[[recent]]
id = "aa6de19c-3c07-48cc-b81c-02f15f5963f3"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T07:39:23.431854+00:00"
pinned = false

[[recent]]
id = "6866be00-c16d-405d-b3e5-854e03bc9c31"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T07:33:39.886462+00:00"
pinned = false

[[recent]]
id = "544799af-4639-4eb7-958b-1e588f4dd885"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T07:19:49.710669+00:00"
pinned = false

[[recent]]
id = "0e79f4db-13b8-4e65-b0a0-6d901cf59d98"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T06:22:32.874664+00:00"
pinned = false

[[recent]]
id = "158a5919-0041-4ccb-95c6-adc22781e144"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T06:08:39.821474+00:00"
pinned = false

[[recent]]
id = "fd3a51bd-3bb4-4f30-a2a1-d183dc588c0e"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T06:06:32.272931+00:00"
pinned = false

[[recent]]
id = "a1492b0d-2944-40b2-ae9e-154ea69e708b"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T05:52:27.945157+00:00"
pinned = false

[[recent]]
id = "4968b908-c94f-439b-a498-da0e741eb2da"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T05:48:31.680661+00:00"
pinned = false

[[recent]]
id = "e33c96d0-343a-4b6d-aa04-e3a01b8d99e3"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T05:40:27.892911+00:00"
pinned = false

[[recent]]
id = "f2f79254-7679-4350-9af1-b02adfc7a370"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T05:38:47.218287+00:00"
pinned = false

[[recent]]
id = "b9a2f7a3-e471-48de-a258-f998c610aab6"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T05:06:03.620456+00:00"
pinned = false

[[recent]]
id = "e70f2cb7-bf70-4baa-866f-ffafad2aa391"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T03:50:57.778450+00:00"
pinned = false

[[recent]]
id = "eb2f5692-5e88-4b0f-9bd6-9c90242282db"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T03:22:32.978007+00:00"
pinned = false

[[recent]]
id = "b107b28a-3d86-4d8c-9599-d8e984bc4bf0"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T03:20:41.679675+00:00"
pinned = false

[[recent]]
id = "1e443571-0bed-41dd-bd9e-af326cf441b6"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T03:19:30.552759+00:00"
pinned = false

[[recent]]
id = "3e50d848-2d19-49cd-a829-4f2f2c2edf9b"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T03:15:45.652184+00:00"
pinned = false

[[recent]]
id = "ebe4f698-4298-467b-a620-f6aa633ff6e4"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T03:12:00.187235+00:00"
pinned = false

[[recent]]
id = "4a2d58aa-c2bf-4260-9be9-54153dbddc6c"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T01:24:00.023737+00:00"
pinned = false

[[recent]]
id = "719734d2-b461-40c4-b319-da37933c4e39"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T01:21:41.188021+00:00"
pinned = false

[[recent]]
id = "0ffc223f-3f2d-467e-a512-633cb3d71c71"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T01:16:55.322891+00:00"
pinned = false
