[[starred]]
id = "e55c6aa7-1103-4d48-8457-12f5cafe62ac"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T05:39:58.353270+00:00"
pinned = true

[[recent]]
id = "ea7daf82-0699-41cb-b26d-58166e422cde"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-07-06T00:07:09.574304+00:00"
pinned = false

[[recent]]
id = "a77486a5-5e97-4216-9b45-b79b87caf45f"
name = "agent"
path = "/Users/jimmie/personal/build-studio-workspaces/agent"
last_accessed = "2025-07-03T18:29:02.450102+00:00"
pinned = false

[[recent]]
id = "badf0f75-e218-49c7-99fb-de0ba14d256e"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-07-03T18:28:46.984988+00:00"
pinned = false

[[recent]]
id = "505bc55c-6d1f-40fc-9fc2-c516378ee181"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-29T06:01:16.066210+00:00"
pinned = false

[[recent]]
id = "107593ad-8394-4498-9e2b-9cd474154621"
name = "agent"
path = "/Users/jimmie/personal/build-studio-workspaces/agent"
last_accessed = "2025-06-28T19:42:40.484558+00:00"
pinned = false

[[recent]]
id = "41aecbaf-82c0-4969-9d1c-2ae092fe48ff"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-28T19:23:28.485141+00:00"
pinned = false

[[recent]]
id = "97a5c6e4-db7d-4503-88d4-01a7211deba0"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-28T19:08:13.338967+00:00"
pinned = false

[[recent]]
id = "ae756a73-8dc1-4555-aa4e-cd033512294e"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-28T19:07:32.565736+00:00"
pinned = false

[[recent]]
id = "76218a2b-a831-4d24-8162-cab3e8b32d92"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-28T17:48:06.941585+00:00"
pinned = false

[[recent]]
id = "185ca6a9-616c-40cd-ae16-c2c2704e0a83"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-28T07:06:30.167955+00:00"
pinned = false

[[recent]]
id = "34e0f823-3ca4-49b5-bae4-a738bff11014"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-28T06:54:49.809117+00:00"
pinned = false

[[recent]]
id = "a189e290-9c72-40fb-8a52-1327150fd49a"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T21:44:38.025718+00:00"
pinned = false

[[recent]]
id = "2be06e71-1711-49fe-9d04-b6bc6e736f5c"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T21:39:59.054686+00:00"
pinned = false

[[recent]]
id = "fb61d488-dec7-4990-8d63-3f84edf74927"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T20:06:00.894531+00:00"
pinned = false

[[recent]]
id = "aa6de19c-3c07-48cc-b81c-02f15f5963f3"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T07:39:23.431854+00:00"
pinned = false

[[recent]]
id = "6866be00-c16d-405d-b3e5-854e03bc9c31"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T07:33:39.886462+00:00"
pinned = false

[[recent]]
id = "544799af-4639-4eb7-958b-1e588f4dd885"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T07:19:49.710669+00:00"
pinned = false

[[recent]]
id = "0e79f4db-13b8-4e65-b0a0-6d901cf59d98"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T06:22:32.874664+00:00"
pinned = false

[[recent]]
id = "158a5919-0041-4ccb-95c6-adc22781e144"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T06:08:39.821474+00:00"
pinned = false

[[recent]]
id = "fd3a51bd-3bb4-4f30-a2a1-d183dc588c0e"
name = "build-studio"
path = "/Users/jimmie/personal/build-studio-workspaces/build-studio"
last_accessed = "2025-06-27T06:06:32.272931+00:00"
pinned = false
